# dataset defaults
alg: simclrmse
aug_type: symmetric
optimizer: LARS
base_lr: 0.3
weight_decay: 1e-6
mlp: "2048-256"
temperature: 0.15

# Adaptive lambda
lambd: 1.0              # = 1 for default SimCLR
base_lr_lambda: 0.03    # = base_lr / 10 by default
tolerance: 0.001