# dataset defaults
alg: vicreg
aug_type: asymmetric
optimizer: LARS
base_lr: 0.3
weight_decay: 1e-6
mlp: "2048-2048-512"
sim-coeff: 25.0
std-coeff: 25.0
cov-coeff: 1.0   

# Adaptive lambda
lambd: 25.0             # = sim-coeff by default
# base_lr_lambda: 0.03    # = base_lr / 10 by default
# tolerance: 0.00001